### ISSUE TITLE
 Installation script fails to move template config to config directory

### ISSUE THREAD

**Issue by FrederikRichter** [lentilus/xk#1]
## Description

When attempting to install the xettelkasten instance, the installation script fails to move the template configuration file to the user's config directory. This occurs despite the script having all necessary permissions.

## Steps to Reproduce

1. Run the xettelkasten installation script
2. Check the config directory for the presence of the template configuration file

## Expected Behavior

The installation script should successfully move the template configuration file to the user's config directory.

## Actual Behavior

The template configuration file is not present in the user's config directory after running the installation script. IT IS MOVED TO /xk/config !!!

## System Information

- OS: Debian GNU/Linux 12 (bookworm) on Windows x86_64
- Kernel: 5.15.153.1-microsoft-standard-WSL2
- Shell: fish 3.6.0

## Additional Notes

The installation was attempted on a WSL2 environment. It's possible that there might be specific issues related to file system operations or permissions in this context.

**Comment by FrederikRichter** [comment]
XDG_CONFIG_HOME="$HOME/.config" was not set and is not by default. I think the installscript should fallback to $HOME/.config.

**Comment by lentilus** [comment]
Thank you very much for submitting this issue. I pushed these two commits: debd3e1 , 1ad838d that should solve your issue - along with some unrelated ones.
Just let me know if things are working now :)
